const card = [
  {
    id: 1,
    image: "./assets/emergency.png",
    title: "National Emergency Number",
    subtitle: "National Emergency",
    call_number: 999,
    definition: "All",
  },
  {
    id: 2,
    image: "./assets/police.png",
    title: "Police Helpline Number",
    subtitle: "Police",
    call_number: 999,
    definition: "Police",
  },
  {
    id: 3,
    image: "./assets/fire-service.png",
    title: "Fire Service Number",
    subtitle: "Fire Service",
    call_number: 999,
    definition: "Fire",
  },
  {
    id: 4,
    image: "./assets/ambulance.png",
    title: "Ambulance Service",
    subtitle: "Ambulance",
    call_number: 1994 - 999999,
    definition: "Health",
  },
  {
    id: 5,
    image: "./assets/emergency.png",
    title: "Women & Child Helpline",
    subtitle: "Women & Child Helpline",
    call_number: 109,
    definition: "Help",
  },
  {
    id: 6,
    image: "./assets/emergency.png",
    title: "Anti-Corruption Helpline",
    subtitle: "Anti-Corruption",
    call_number: 106,
    definition: "Govt",
  },
  {
    id: 7,
    image: "./assets/emergency.png",
    title: "Electricity Helpline",
    subtitle: "Electricity Outage",
    call_number: 16216,
    definition: "Electricity",
  },
  {
    id: 8,
    image: "./assets/emergency.png",
    title: "Brac Helpline",
    subtitle: "Brac",
    call_number: 16445,
    definition: "NGO",
  },
  {
    id: 9,
    image: "./assets/emergency.png",
    title: "Bangladesh Railway Helpline ",
    subtitle: "Bangladesh Railway",
    call_number: 163,
    definition: "Travel",
  },
];
